import { AppLanguage } from "@/src/core/types";

export const TEXT = {
  zh: {
    tabs: {
      home: "首页",
      status: "状态",
      trends: "趋势",
      settings: "设置",
    },
    common: {
      yes: "是",
      no: "否",
      loading: "加载中...",
      none: "无",
      clear: "清除",
      save: "保存",
      cancel: "取消",
      confirm: "确定",
    },
    home: {
      title: "摸鱼计时器",
      configured: "已配置",
      notConfigured: "未配置",
      redirectingToSettings: "正在跳转到设置页...",
      workWindow: "工作时段",
      inWorkTime: "上班时间内",
      outWorkTime: "非上班时间",
      todaySlacking: "今日摸鱼",
      stopSlacking: "结束摸鱼",
      startSlacking: "开始摸鱼",
      loadingData: "正在加载本地数据...",
    },
    status: {
      title: "状态",
      historyTitle: "最近七天状态切换明细",
      settingsTitle: "设置",
      noRecords: "暂无记录",
      currentEffective: "当前生效设置",
      historicalEffective: "历史设置",
      startDate: "开始日期",
      endDate: "结束日期",
      notRecorded: "未记录",
      switchOn: "开",
      switchOff: "关",
      today: "今天",
      loading: "加载",
      records7d: "7天记录数",
      saves7d: "7天设置保存数",
      total7d: "7天总时长",
      avg7d: "7天日均",
      todayRatio: "今日占比",
      lastSave: "最近一次保存",
      last7d: "最近7天",
    },
    trends: {
      title: "7天趋势",
      total: "总计",
      average: "平均",
      todayVsAvg: "今日对比平均",
    },
    settings: {
      title: "设置",
      configured: "已配置",
      language: "语言",
      sectionWorkTime: "工作时间",
      enableLunchBreak: "午休时间",
      sectionWorkDays: "工作日选择",
      workStart: "上班开始",
      workEnd: "上班结束",
      lunchStart: "午休开始（可选）",
      lunchEnd: "午休结束（可选）",
      notSet: "未设置",
      workDays: "工作日",
      saveSchedule: "保存设置",
      toggleLanguage: "切换语言",
      toggleConfigured: "切换配置状态",
      recentSaves: "最近保存记录",
      noSaveHistory: "暂无保存记录",
      saved: "已保存",
      timeFormat: "时间格式必须是 HH:mm",
    },
  },
  en: {
    tabs: {
      home: "Home",
      status: "Status",
      trends: "Trends",
      settings: "Settings",
    },
    common: {
      yes: "yes",
      no: "no",
      loading: "Loading...",
      none: "none",
      clear: "Clear",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
    },
    home: {
      title: "SlackingOffTimer Mobile",
      configured: "Configured",
      notConfigured: "Not configured",
      redirectingToSettings: "Redirecting to settings...",
      workWindow: "Work window",
      inWorkTime: "In work time",
      outWorkTime: "Out of work time",
      todaySlacking: "Today slacking",
      stopSlacking: "Stop Slacking",
      startSlacking: "Start Slacking",
      loadingData: "Loading local data...",
    },
    status: {
      title: "Status",
      historyTitle: "Last 7 days switch details",
      settingsTitle: "Settings",
      noRecords: "No records",
      currentEffective: "Current effective settings",
      historicalEffective: "Historical settings",
      startDate: "Start date",
      endDate: "End date",
      notRecorded: "Not recorded",
      switchOn: "ON",
      switchOff: "OFF",
      today: "Today",
      loading: "Loading",
      records7d: "Slacking records (7d)",
      saves7d: "Schedule saves (7d)",
      total7d: "Total slacking (7d)",
      avg7d: "Daily avg (7d)",
      todayRatio: "Today ratio",
      lastSave: "Last schedule save",
      last7d: "Last 7 Days",
    },
    trends: {
      title: "7-Day Trends",
      total: "Total",
      average: "Average",
      todayVsAvg: "Today vs Avg",
    },
    settings: {
      title: "Settings",
      configured: "Configured",
      language: "Language",
      sectionWorkTime: "Work Time",
      enableLunchBreak: "Lunch Break",
      sectionWorkDays: "Work Days",
      workStart: "Work Start",
      workEnd: "Work End",
      lunchStart: "Lunch Start (optional)",
      lunchEnd: "Lunch End (optional)",
      notSet: "Not set",
      workDays: "Work Days",
      saveSchedule: "Save Schedule",
      toggleLanguage: "Toggle Language",
      toggleConfigured: "Toggle Configured",
      recentSaves: "Recent Schedule Saves",
      noSaveHistory: "No save history yet.",
      saved: "Saved",
      timeFormat: "Time format must be HH:mm",
    },
  },
} as const;

export const t = (language: AppLanguage) => TEXT[language];
