import type { AppLanguage } from "./types";

export const TEXT = {
  zh: {
    // 通用
    appTitle: "SlackingOff",
    loading: "加载中...",
    save: "保存",
    // 导航
    home: "首页",
    trends: "统计",
    settings: "设置",
    // 设置页
    settingsLoading: "正在加载设置...",
    sectionLanguage: "语言",
    languageZh: "中文",
    languageEn: "EN",
    sectionWorkTime: "工作时间",
    sectionLunchTime: "午休时间",
    sectionWorkDays: "工作日选择",
    saveSettings: "保存设置",
    savingSettings: "保存中...",
    resetSettings: "取消修改",
    saveSuccessTitle: "保存成功",
    saveSuccessMsg: "设置已更新并缓存到本地",
    saveFailTitle: "保存失败",
    saveFailMsg: "请稍后重试",
    settingsErrorTitle: "设置有误",
    settingsCacheHint: "设置会自动缓存到本地，重启应用后仍然保留。",
    configuredHint: "已完成初始化配置",
    firstConfigHint: "首次配置中",
    currentStatus: "当前状态：",
    // 星期
    weekSun: "周日",
    weekMon: "周一",
    weekTue: "周二",
    weekWed: "周三",
    weekThu: "周四",
    weekFri: "周五",
    weekSat: "周六",
    // 状态卡
    standby: "待机",
    tracking: "计时中",
    offWork: "非工作时段",
    waitingForWork: "等待上班...",
    todayTitle: "今日总览",
    fishDuration: "今日计时时长",
    fishRatio: "计时占比",
    status: "当前状态",
    startSession: "开始计时",
    stopSession: "结束计时",
    notWorkHint: "当前不在工作时段，无法开始会话。",
    // 统计页
    sevenDaysTitle: "最近 7 天趋势",
    noDataHint: "暂无数据，先去首页开始一次会话。",
    total7: "7天总计",
    dailyAverage: "日均时长",
    trendChart: "趋势图",
    avgRatio: "平均占比",
    durationLegend: "时长",
    ratioLegend: "占比",
    // 校验错误
    errNeedWorkTime: "请填写上下班时间",
    errOrderWorkTime: "上班时间必须早于下班时间",
    errBothLunch: "午休开始和结束需要同时填写",
    errOrderLunch: "午休开始必须早于午休结束",
    errLunchRange: "午休时间必须在工作时间内",
    errNeedWorkDay: "至少选择一个工作日",
  },
  en: {
    // General
    appTitle: "SlackingOff",
    loading: "Loading...",
    save: "Save",
    // Navigation
    home: "Home",
    trends: "Stats",
    settings: "Settings",
    // Settings page
    settingsLoading: "Loading settings...",
    sectionLanguage: "Language",
    languageZh: "中文",
    languageEn: "EN",
    sectionWorkTime: "Work Hours",
    sectionLunchTime: "Break Time",
    sectionWorkDays: "Work Days",
    saveSettings: "Save Settings",
    savingSettings: "Saving...",
    resetSettings: "Discard",
    saveSuccessTitle: "Saved",
    saveSuccessMsg: "Settings updated and saved locally",
    saveFailTitle: "Save Failed",
    saveFailMsg: "Please try again",
    settingsErrorTitle: "Invalid Settings",
    settingsCacheHint: "Settings are saved locally and restored after restart.",
    configuredHint: "Setup complete",
    firstConfigHint: "First-time setup",
    currentStatus: "Current status: ",
    // Weekdays
    weekSun: "SUN",
    weekMon: "MON",
    weekTue: "TUE",
    weekWed: "WED",
    weekThu: "THU",
    weekFri: "FRI",
    weekSat: "SAT",
    // Status card
    standby: "Standby",
    tracking: "Tracking",
    offWork: "Off Work",
    waitingForWork: "Waiting for work...",
    todayTitle: "Today Overview",
    fishDuration: "Slacking Duration",
    fishRatio: "Slacking Ratio",
    status: "Status",
    startSession: "Start Slacking",
    stopSession: "End Slacking",
    notWorkHint: "Out of work window. Session cannot start.",
    // Trends page
    sevenDaysTitle: "Last 7 Days",
    noDataHint: "No data yet. Start one session from Home.",
    total7: "7-Day Total",
    dailyAverage: "Daily Average",
    trendChart: "Trend Chart",
    avgRatio: "Avg Ratio",
    durationLegend: "Duration",
    ratioLegend: "Ratio",
    // Validation errors
    errNeedWorkTime: "Please fill in start and end time",
    errOrderWorkTime: "Start time must be earlier than end time",
    errBothLunch: "Break start and end must both be filled",
    errOrderLunch: "Break start must be earlier than break end",
    errLunchRange: "Break time must be within work hours",
    errNeedWorkDay: "Select at least one work day",
  },
} as const;

export type LocaleText = (typeof TEXT)[AppLanguage];

export function t(language: AppLanguage): LocaleText {
  return TEXT[language];
}
